version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/loganalyzer
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - uploads:/app/uploads
    command: npm run dev

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  uploads: